### ISSUE TITLE
Publish v1

### ISSUE THREAD

**Issue by chadfawcett** [TwoStoryRobot/express-joi-middleware#1]
@chrisfosterelli We have extracted this code at least 3 or 4 times now to implement into new projects which is why I decided to make it into a package. Since you were the author of this code I wanted to get you to take a look over it before I publish v1. See if I'm missing anything or if you envisioned any other features for this middleware.

@TwoStoryRobot/devs I would like to publish this publicly under the MIT license. While this package is fairly simple, I find it useful and others might too. It also makes it easier for us to install as it doesn't require npm authentication. Thoughts?

**Comment by jonotron** [comment]
This looks pretty straight forward to me. :+1: for MIT and publishing. Though I see there is this: https://www.npmjs.com/package/express-joi-validator which looks essentially the same, but the GitHub repo is no more.

**Comment by chadfawcett** [comment]
@jonotron Yeah I saw this and another package, I liked the simplicity of our code, and the API difference. https://github.com/goodeggs/express-joi-validator

**Comment by chrisfosterelli** [comment]
LGTM! 👍

**Comment by chadfawcett** [comment]
Published! :shipit: https://www.npmjs.com/package/@twostoryrobot/express-joi-middleware
