### ISSUE TITLE
Resolve security vulnerabilities

### ISSUE THREAD

**Issue by chadfawcett** [TwoStoryRobot/express-joi-middleware#4]
The dependencies need to be updated to resolve the security issues. https://github.com/TwoStoryRobot/express-joi-middleware/network/alerts

Ideally we could setup the Renovate bot to keep the dependencies up to date.

**Comment by chrisfosterelli** [comment]
@okanji Are you still planning to resolve this one?

**Comment by chrisfosterelli** [comment]
Closing as this is no longer maintained
